language: node_js
node_js:
  - '0.12'

env:
  global:
    secure: kuBAVUYuzOSOhqDjMvFad8FD/as1OBBj6HdeOJWm9zCohv4LG6UiB7YD0h1aNZPzSprqV7JJYW9X9ZnAbg+CLfb/gr35AW6kc1Y+LkUiyuR6wY34ylYKyL9oov3Pso+MmLUYmgTHBQJenqgD/S2GhZ80cMFUVMSzqPwdANBKA5M=

addons:
  apt:
    packages:
    - fontforge 
    - ttfautohint

before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install
  - bower install

script:
  - npm test

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "integration" && grunt deployQA
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && grunt deployProd
